before:
  hooks:
  - go mod tidy

builds:
- env:
  - CGO_ENABLED=0
  goos:
  - linux
  - darwin
  goarch:
  - amd64
  - arm64
  ignore:
  - goos: linux
    goarch: arm64

archives:
- format: binary
  replacements:
    darwin: Darwin
    linux: Linux
    amd64: x86_64

release:
  github:
    owner: bitrise-io
    name: bitrise
  draft: true
  mode: replace

checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ incpatch .Version }}-next"
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
