format_version: "15"
default_step_lib_source: https://github.com/bitrise-io/bitrise-steplib.git

include:
- path: modular_config_module.yml

workflows:
  print_hello_bitrise:
    envs:
    - NAME: Bitrise
    steps:
    - script:
        inputs:
        - content: echo "Hello $NAME!"
